# ray worker image with octave runtime
FROM rayproject/ray:latest
RUN sudo apt-get update && sudo apt-get install --no-install-recommends -y  octave octave-common octave-communications octave-communications-common gnuplot