{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(exported_job)" } }
  ]
 },
 "panels": [
  {
   "title": "Success",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpc_correct_success_total{exported_job=\"$job\"}",
     "legendFormat": "{{errors}}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpc_job_executed_total{exported_job=\"$job\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(hpc_job_executed_total{exported_job=\"$job\"}[1m])",
     "legendFormat": "job/s"
    }
   ]
  },
  {
   "title": "Batch info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "hpc_batch_exec{exported_job=\"$job\"}",
     "legendFormat": "Execution Time"
    },
    {
     "expr": "hpc_batch_gen{exported_job=\"$job\"}",
     "legendFormat": "Generate Time"
    }
   ]
  },
  {
   "title": "Job executed pre second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(hpc_job_executed_total{exported_job=\"$job\"}[1m]))",
     "legendFormat": "Job executed pre second"
    }
   ]
  }
 ]
}